openapi: 3.0.0
info:
  title: Credits
  description:
    This application allows you to obtain the information about the credits.
  version: 1.0.0
servers:
  - url: https://localhost:8081
tags:
  - name: credits
    description: Everything about your credits.
paths:
  /credit:
    post:
      tags:
        - credits
      summary: Allows you to register a credit of a customer
      description: Allows you to register a credit of a person or a company
      operationId: createCredit
      requestBody:
        required: true
        description: Allows to register a credit.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
      responses:
        '201':
          description: Credit registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit'
        '400':
          description: Credit request rejected

    patch:
      tags:
        - credits
      summary: Allows you to pay your credit.
      description: allows you to pay your credit.
      operationId: payCredit
      requestBody:
        required: true
        description: Allows you to pay your credit.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditPay'
      responses:
        '200':
          description: The credit was paid correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit'
        '400':
          description: Invalid Request
        '404':
          description: Customer or Credit number are invalid

  /credit/client/{clientDocument}:
    get:
      tags:
        - credits
      summary: Allows you to consult information about your credit.
      description: Allows you to consult information about your credit like amounts.
      operationId: consultCredit
      parameters:
        - name: clientDocument
          in: path
          description: Client Document
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The consult was made correctly
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Credit'
        '400':
          description: Invalid Request
        '404':
          description: Customer or Card are invalid

components:
  schemas:
    CreditRequest:
      required:
        - amount
        - clientDocument
      type: object
      properties:
        amount:
          type: number
          format: double
        clientDocument:
          type: string
    CreditPay:
      required:
        - amount
        - creditNumber
      type: object
      properties:
        amount:
          type: number
          format: double
        creditNumber:
          type: string
    Credit:
      type: object
      properties:
        message:
          type: string

